### ISSUE TITLE
Date fields throw BadRequest

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns-python#52]
Ran the following commands:

>>> client = VinylDNSClient("http://localhost:9000", "xxx", "xxx")
>>> existing_txt = [rs for rs in existing_records.record_sets if rs.type == "TXT"][0]
>>> data_to_add = TXTData("some-test-txt-to-add")
>>> existing_txt.records.append(data_to_add)
>>> existing_txt.records
[<vinyldns.record.TXTData object at 0x102e970f0>, <vinyldns.record.TXTData object at 0x102e53e48>]
>>> updated = client.update_record_set(existing_txt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rstar201/Desktop/Vinyl/python/vinyldns-python/src/vinyldns/client.py", line 519, in update_record_set
    to_json_string(record_set), **kwargs)
  File "/Users/rstar201/Desktop/Vinyl/python/vinyldns-python/src/vinyldns/client.py", line 157, in __make_request
    return self.__check_response(response)
  File "/Users/rstar201/Desktop/Vinyl/python/vinyldns-python/src/vinyldns/client.py", line 164, in __check_response
    raise BadRequestError(response.text)
vinyldns.client.BadRequestError: {"errors":["Invalid date format 2019-06-25T16:37:09+00:00"]}

the api doesnt use created/update on an update_recordset call anyway, so i just cleared those fields to avoid it, but we should fix to make sure people dont run into this same issue

**Comment by Alig1493** [comment]
I can take a look at this issue if it's alright.
